#!/usr/bin/php

<?php

use Scaleplan\Access\AccessModify;

/** @var AccessModify $am */
$am = AccessModify::create(0);

if ($argv[1] === 'schema' || $argv[2] === 'schema') {
    /**
     * Иницализация схемы хранения
     */
    $am->initSQLScheme();
}

if ($argv[1] === 'data' || $argv[2] === 'data') {
    /**
     * Генерация
     */
    $am->initPersistentStorage();
}
